### PR TITLE
make `ignore_seek_speed` default to false.

### PR DESCRIPTION
**Pull request by IntangibleMatter**
Modify this behaviour to be consistent with FMOD's api.

### CODE REVIEW

**Comment by alessandrofama** [comment]
You did add `DEFVAL` macro to the ``StudioSystem`` method bindings, but not to the ``EventInstance`` one's.  🙂

**Comment by IntangibleMatter** [comment]
oop! on it

**Comment by IntangibleMatter** [comment]
Amended to commit!

**Comment by alessandrofama** [comment]
When you amend a previous commit, you still have to force push the changes. Right now I’m not seeing the changes you applied to this PR. See „Modifying Pull Request“ in Godot‘s docs.

**Comment by IntangibleMatter** [comment]
ugh, sorry. Done!

**Comment by alessandrofama** [comment]
Fixed in #20.

**Pull request closed without merging**
