### PR TITLE
Make `ignore_seek_speed` default to false.

### PR DESCRIPTION
**Pull request by IntangibleMatter**
`ignore_seek_speed` has a default value of false in the FMOD api, however this is missing in this version, creating redundant code that's inconsistent with what FMOD states.

I could not test this as I have run into issues building this repository before (straight from source), but the changes are minimal enough  that there should be no issues.

### CODE REVIEW

**Comment by IntangibleMatter** [comment]
Wondering if this PR will be reviewed anytime soon?

**Comment by alessandrofama** [comment]
In the Godot convention, it's recommended to place the default value within the function declaration itself, as shown below:

```
// studio_api.h
bool set_parameter_by_name(const String& name, float value, bool ignore_seek_speed = false) const;
```

Additionally, it's important to include the DEFVAL macro when binding the methods as well, as demonstrated in the following code:
```
// studio_api.cpp
	ClassDB::bind_method(D_METHOD("set_parameter_by_name", "name", "value", "ignore_seek_speed"),
			&StudioSystem::set_parameter_by_name, DEFVAL(false));
```

By adopting this approach, there's no necessity to duplicate default parameters within the CPP definitions. It's worth noting that without utilizing the DEFVAL macro, the method binding doesn't seem to apply the default parameter to GDScript.

If you rebase and make adjustments to this pull request, it should be OK for me. Thank you for considering contributing, and it's great that the proposed changes are in line with the FMOD API approach!

**Comment by IntangibleMatter** [comment]
Should be good! Sorry for the issues, I've never really done C++ before :sweat_smile:

**Comment by alessandrofama** [comment]
I just saw you've created this PR from your main branch. So by rebasing you just added my latest commits to your PR.
I would suggest you re-fork and recreate the PR using Godot's [Pull request workflow](https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html).

**Comment by IntangibleMatter** [comment]
Will do.

**Pull request closed without merging**
